// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDDE5iXHtwT97_JoIEonkU_dmqOrtv1w',
    appId: '1:638140820687:android:311eb708669eb5c27f1bba',
    messagingSenderId: '638140820687',
    projectId: 'cash-note-fe21a',
    storageBucket: 'cash-note-fe21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzKZzS9edGwvCll1YQ4XaHrio-7d0EoYg',
    appId: '1:638140820687:ios:38df6a3e21b0f54e7f1bba',
    messagingSenderId: '638140820687',
    projectId: 'cash-note-fe21a',
    storageBucket: 'cash-note-fe21a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvNRGD4CAgUrE8TrIRi48p6AoM9nn_5s',
    appId: '1:638140820687:web:c3a73710aba6d3be7f1bba',
    messagingSenderId: '638140820687',
    projectId: 'cash-note-fe21a',
    authDomain: 'cash-note-fe21a.firebaseapp.com',
    storageBucket: 'cash-note-fe21a.firebasestorage.app',
    measurementId: 'G-PWJ41ZNLC0',
  );
}
